# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Anbindung von KNX Bussystemen via KNX-IP'
        en: 'Establishes connections to KNX bus systems'
        fr: 'Connexion de systèmes KNX via KNX-IP'
    maintainer: thesing
    tester: 
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.0.0                 # Plugin version
    sh_minversion: 1.4             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: KnxEts                 # class containing the plugin
    attribute_prefix: knx          # prefix of the item-attributes, so attributes have to start with 'knx_'

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    time_ga:
        type: knx_ga
        description:
            de: 'Gruppenadresse, um die Uhrzeit an den Knx-Bus zu senden'
            en: 'groupadress to send a timestamp to the knx bus'

    date_ga:
        type: knx_ga
        description:
            de: 'Gruppenadresse, um das Datum an den Knx-Bus zu senden'
            en: 'groupadress to send the date to the knx bus'

    send_time:
        type: int
        default: 0
        description:
            de: 'Zeitintervall zum Senden von Uhrzeit und Datum an den KNX-Bus'
            en: 'time interval to send time and date to the knx bus'

    busmonitor:
        type: str
        default: 'off'
        valid_list:
          - 'on'
          - 'off'
          - 'true'
          - 'false'
          - 'logger'
        description:
            de: "Wenn auf 'on'/'true' gesetzt, wird jedes KNX-Paket im Standard-Logger protokolliert. Wenn 'logger' eingestellt ist, werden alle KNX-Meldungen in einem separaten Logger 'knx_busmonitor' protokolliert."
            en: "If set to 'on'/'true' every KNX packet will be logged to the default plugin logger. If set to 'logger', all knx messages will be logged to a separate logger 'knx_busmonitor'"

    host:
        type: ipv4
        default: '127.0.0.1'
        description:
            de: 'IP Adresse des Computers auf dem der EIB Daemon bzw. KNX Daemon läuft. Standard: Auf dem Computer auf dem SmartHomeMG läuft.'
            en: 'IP address of the computer the eib daemon or knx daemon is running on. Default: The Daemon is running on the computer SmartHomeNG is running on.'

    port:
        type: int
        default: 6720
        description:
            de: 'Port, der bei der Kommunikation mit dem Eibd- oder Knxd-Daemon verwendet wird'
            en: 'Port to be used when communicating to eibd or knxd daemon'

    readonly:
        type: bool
        default: False
        description:
            de: 'Wenn der Wert auf "True" gesetzt ist, liest das Plugin nur den KNX-Bus und sendet keine Nachrichten an den Bus.'
            en: 'If set to True, the plugin only read the knx bus and send no group message to the bus.'

    enable_stats:
        type: bool
        default: True
        description:
            de: 'Wenn diese Option auf "True" gesetzt ist, werden die Statistikfunktionen aktiviert um Daten erfassen'
            en: 'if set to True, the statistic functions are enabled to collect data'



item_attributes:
    # Definition of item attributes defined by this plugin
    knx_dpt:
        type: str
        valid_list:
         - '1'
         - '2'
         - '3'
         - '4002'
         - '4.002'
         - '5'
         - '5001'
         - '5.001'
         - '6'
         - '7'
         - '8'
         - '9'
         - '10'
         - '11'
         - '12'
         - '13'
         - '14'
         - '16000'
         - '16'
         - '16001'
         - '16.001'
         - '17'
         - '20'
         - '24'
         - '232'
        description:
            de: 'Dieses Attribut setzt den Typ des KNX-Datenpunktes, der für die Konvertierung der KNX-Nachrichten in das interne SmartHomeNG-Format verwendet wird. Die Angabe ist zwingend erforderlich ist. Wenn Sie keinen Wert angeben, wird das Element vom Plugin ignoriert. Der DPT muss dem Typ des Artikels entsprechen!'
            en: "This attribute set the KNX datapoint type used for conversion of the KNX messages to internal SmartHomeNG format. It is mandatory. If you don't provide one the item will be ignored by the plugin. The DPT has to match the type of the item! BE CAREFUL to put the value in quotes to ensure they are interpreted as strings and not as numbers!"

    knx_send:
        type: list(knx_ga)
        description:
            de: 'Gruppenadresse, an die gesendet werden soll, wenn das Element geändert wird. Sie können eine oder mehrere Gruppenadressen angeben.'
            en: 'Group address to send to, if the item is changed. You could specify one or more group addresses.'

    knx_listen:
        type: list(knx_ga)
        description:
            de: 'Gruppenadresse (oder Liste von Gruppenadressen), auf die gehört werden soll. KNX-Nachrichten an diese Gruppenadresse(n) ändern den Wert des Items'
            en: "Group address (or list of group addresses) to listen for. KNX messages to this group address(es) will change the item's value"

    knx_init:
        type: knx_ga
        description:
            de: 'Gruppenadresse für die Initialisierung des Items. Der KNX-Bus wird nach dem Wert abgefragt. Die Angabe impliziert knx_listen, also muss knx_listen nicht für diese Gruppenadresse angegeben werden.'
            en: 'Group address to use for initialization of the item. The KNX bus is queried for the value. It implies knx_listen, so knx_listen need not to be specified for this group address.'

    knx_cache:
        type: knx_ga
        description:
            de: 'Gruppenadresse für die Initialisierung des Items. Der Wert wird aus dem Cache von KNXD/EIBD gelesen. Wenn kein Cache-Wert vorhanden ist, wird der KNX-Bus nach dem Wert abgefragt. Die Angabe impliziert knx_listen, also muss knx_listen nicht für diese Gruppenadresse angegeben werden.'
            en: 'Group address to use for initialization of the item. The value is read from the cache of KNXD/EIBD. If no cached value exists, the KNX bus is queried for the value. It implies knx_listen, so knx_listen need not to be specified for this group address.'

    knx_reply:
        type: list(knx_ga)
        description:
            de: 'Eine oder mehrere Gruppenadressen angeben, um den Objektwert vom KNX-Bus aus lesen zu können.'
            en: 'Specify one or more group addresses to allow reading the item value from the KNX bus.'

    knx_status:
        type: list(knx_ga)
        description:
            de: 'Ähnlich wie bei knx_send, sendet aber auch bei Änderungen über KNX, wenn sich der knx_status GA vom Ziel-GA unterscheidet. Sie können eine oder mehrere Gruppenadressen angeben.'
            en: 'Similar to knx_send but will send updates even for changes via KNX if the knx_status GA differs from the destination GA. You could specify one or more group addresses.'

    knx_poll:
        type: list(2,knx_ga,int)
        description:
            de: 'Geben Sie eine abzurufende Gruppenadresse und das Zeitintervall in Sekunden für eine automatisierte Abfrage vom KNX Bus in Form einer Liste an. Der erste Eintrag ist die Gruppenadresse, der zweite Eintrag ist das Pollintervall in Sekunden. Dies kann für Aktoren oder Sensoren verwendet werden, die keine regelmäßige Übermittlung von Werten unterstützen.'
            en: 'Specify a group address to poll and the time interval in seconds for an automated query of KNX in form of a list. First entry is the group address, second entry is the poll interval in seconds. This may be used for actors or sensors that do no support a regular sending of values themselves.'


logic_trigger_attributes:
    # Definition of logic trigger attributes defined by this plugin
    knx_dpt:
        type: str
        valid_list:
         - '1'
         - '2'
         - '3'
         - '4002'
         - '4.002'
         - '5'
         - '5001'
         - '5.001'
         - '6'
         - '7'
         - '8'
         - '9'
         - '10'
         - '11'
         - '12'
         - '13'
         - '14'
         - '16000'
         - '16'
         - '16001'
         - '16.001'
         - '17'
         - '20'
         - '24'
         - '232'
        description:
            de: 'Dieses Attribut setzt den Typ des KNX-Datenpunktes, der für die Konvertierung der KNX-Nachrichten in das interne SmartHomeNG-Format verwendet wird. Die Angabe ist zwingend erforderlich ist. Wenn Sie keinen Wert angeben, wird das Element vom Plugin ignoriert. Der DPT muss dem Typ des Artikels entsprechen!'
            en: "This attribute set the KNX datapoint type used for conversion of the KNX messages to internal SmartHomeNG format. It is mandatory. If you don't provide one the item will be ignored by the plugin. The DPT has to match the type of the item!"

    knx_listen:
        type: list(knx_ga)
        description:
            de: 'Gruppenadresse (oder Liste von Gruppenadressen), auf die gehört werden soll. KNX-Nachrichten an diese Gruppenadresse(n) ändern den Wert des Items'
            en: "Group address (or list of goup addresses) to listen for. KNX messages to this group address will change the item's value"

    knx_reply:
        type: list(knx_ga)
        description:
            de: 'Eine oder mehrere Gruppenadressen angeben, um den Objektwert vom KNX-Bus aus lesen zu können.'
            en: 'Specify one or more group addresses to allow reading the item value from the KNX bus.'

